language: android
jdk: oraclejdk8
sudo: false
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-26

licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - 'android-sdk-preview-license-.+'

script: ./gradlew testDebugUnitTest